version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly" # daily, weekly, monthly ได้
    open-pull-requests-limit: 10
    versioning-strategy: widen # หรือ auto, increase, lockfile-only
    reviewers:
      - "eakapongcdv" 
    target-branch: "main" 